builds:
  - binary: eini
    ldflags: -s -w -X=github.com/jeffutter/eini.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    hooks:
      post: ./upx.sh
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
